
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox LinearLayout;

	private global::Gtk.DrawingArea Graph;

	private global::Gtk.Button Run;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.LinearLayout = new global::Gtk.VBox();
		this.LinearLayout.Name = "LinearLayout";
		this.LinearLayout.Spacing = 6;
		// Container child LinearLayout.Gtk.Box+BoxChild
		this.Graph = new global::Gtk.DrawingArea();
		this.Graph.Name = "Graph";
		this.LinearLayout.Add(this.Graph);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.LinearLayout[this.Graph]));
		w1.Position = 0;
		// Container child LinearLayout.Gtk.Box+BoxChild
		this.Run = new global::Gtk.Button();
		this.Run.CanFocus = true;
		this.Run.Name = "Run";
		this.Run.UseUnderline = true;
		this.Run.Label = global::Mono.Unix.Catalog.GetString("Run");
		this.LinearLayout.Add(this.Run);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.LinearLayout[this.Run]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add(this.LinearLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Run.Clicked += new global::System.EventHandler(this.OnRunClicked);
	}
}
